[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
ignored_error_codes = [5667, 2072, 6321, 5574, 2018, 3860]
evm_version = "cancun"
remappings = ["@exercises/=src/exercises/"]

[fmt]
line_length = 80

[profile.solution]
remappings = ["@exercises/=src/solutions/"]
